### ISSUE TITLE
[Feature Request] Upload Docker Image to Docker-Hub with CI/CD Pipeline

### ISSUE THREAD

**Issue by benedikt-weyer** [datasnack/datahub#1]
I think it would be cool if the Datahub-Docker-Image would be uploaded to Docker-Hub.
This could be realized with GitHub Actions.

This would make development and deployment of Datahub much easier.

**Comment by stroebjo** [comment]
yes, that would definitely help! ;)

The images should now be builded for new releases via GitHub Actions and then be uploaded to the GitHub Container Registry (https://github.com/datasnack/datahub/pkgs/container/datahub).

**Comment by benedikt-weyer** [comment]
Thank you, works flawlessly!
